######################################################################
# Automatically generated by qmake (3.1) Mon May 9 22:06:11 2022
######################################################################

TEMPLATE = lib
TARGET = qtc
INCLUDEPATH += .

DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += header/*.h
SOURCES += src/*.cpp
LIBS += -lqtc
QT += widgets
QT += core
QT += gui
